# import UserOrExceptions from 'apps/schema.gql'

type Login {
    user: User,
    token: String
}

union LoginOrExceptions = Login | Exceptions
type Mutation {
    login (email: String!, password: String!): LoginOrExceptions
}
