scalar UUID
scalar any
scalar Upload

directive @loginRequired(exception: Boolean = false, verified: Boolean = true) on FIELD_DEFINITION

type Exception {
    path: String,
    message: String,
    code: String!,
    data: any
}

type Exceptions {
    exceptions: [Exception!]!
}

type Done {
    done: Boolean
}

type User {
    id: ID,
    email: String,
    name: String,
    verified: Boolean
}

type File {
    id: ID!
    path: String!
    filename: String!
    mimetype: String!
    encoding: String!
}

union UserOrExceptions = User | Exceptions
union DoneOrExceptions = Done | Exceptions
