scalar UUID
scalar any

type Exception {
    path: String,
    message: String,
    code: String!,
    data: any
}

type Exceptions {
    exceptions: [Exception!]!
}

type Done {
    done: Boolean
}

type User {
    id: UUID!,
    email: String,
    name: String
}

union UserOrExceptions = User | Exceptions
union DoneOrExceptions = Done | Exceptions
