# import UserOrExceptions from 'apps/common.gql'

type Mutation {
    registerWithPassword (email: String!, password: String!, name: String!): UserOrExceptions
    loginWithPassword (email: String!, password: String!): UserOrExceptions
    resetPassword (email: String!, otp: Int!, password: String!): UserOrExceptions
}
