# import User from 'apps/common.gql'

type Query {
    me: User
}

type Mutation {
    logout (fromAll: Boolean = false): Boolean
    testRegister (email: String!, name: String!): User
    testLogin (email: String!): User
    updateName (name: String!): DoneOrExceptions
}
