# import User from 'apps/common.gql'

type Query {
    me: User
}

type Mutation {
    logout (fromAll: Boolean = false): Boolean
    updateName (name: String!): DoneOrExceptions
    sendVerificationEmail (email: String!, redirect: String!): Boolean
}
